apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statfulset
  namespace: mysql-ns

spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLables:
      app: mysql
  template:
    matchLabels:
      metadata:
        app: mysql

      spec:
        containers:
          - name: mysql-statefulset-pod
            image: mysql:8.0
            ports:
              - containerPort: 3306
            resoures:
              requests:
                cpu: 300m
                memory: 300Mi
              limits:
                cpu: 400m
                memory: 400Mi

            envFrom:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretRef:
                    name: mysql-secret-db
                    key: MYSQL_ROOT_PASSWORD  

              - name: MYSQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: mysql-configmap-db
                    key: MYSQL_DATABASE


            volumeMounts:
              - name: mysql-storage-path
                mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-data-claim-pvc
    spec:
      accessMode: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi




