apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: mysql-ns
  labels:
    app: mysql


spec:
  serviceName: mysql-svc
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
      annotations:
        pod-level-annotation: "true"

    spec:
      
      tolerations:
        - key: "prod"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      containers:
        - name: mysql-statefulset-pod
          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-db
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE_PASS
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-db
                  key: MYSQL_DATABASE_PASS

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 20

          volumeMounts:
            - name: mysql-data-claim-pvc
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-data-claim-pvc

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: standard

        resources:
          requests:
            storage: 2Gi
