apiVersion: v1
kind: Pod
metadata:
  name: test-init-pod
  namespace: initpod

spec:

  initCantainers: 
  - name: initail-container
    image: busybox:latest
    command: ["sh", "-c", "echo 'this container is initail-container..'; slepp 5s;"]

  containers:
  - name: main-conatsiner
    iamge: busybox:latest
    command: ["sh", "-c", "echo 'this is main container started....'"]

