# version: '3.11'

# services:
#   web-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: docker-app:v2.2
#     container_name: docker-container-v2.2
    
#     volumes:
#       - /docker-mount/logs:/project-app/logs 

#     ports:
#       - "9000:9000"

services:
  server-app:
    build:
      context: .   # current path using . 
      dockerfile: Dockerfile 
    image: ${DOCKER_USER_NAME}/app-images-python:latest    # create image by using this one name
    container_name: new-py-container                       # container name 

    ports:
      - "9000:9000"

    volumes:
      - custom-volume:/project-app/logs                    # add custom volume path 

    networks:
      - custom-network                            # create custom network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 5s
      timeout: 8s
      retries: 10
      # start_period: 30s

volumes:
  custom-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-mount/logs

networks:
  custom-network:
    driver: bridge





