version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: ${DOCKER_USER_NAME}/app-latest-lunch-images
    container_name: latest-lunch-container

    develop:
      watch:
        - action: sync
          path: .
          target: /project-app
        - action: rebuild
          path: requirements.txt

    ports:
      - "9000:9000"      

    volumes:
      - custom-volume-app:/project-app/logs

    networks:
      - custom-network-app


  redis:
    image: redis:latest
    container_name: redis-cahe
    ports:
      - "6379:6379"
    networks:
      - custom-network-app
    volumes:
      - custom-volume-app:/project-app/logs


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 6s

volumes:
  custom-volume-app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mount-app/logs

networks:
  custom-network-app:
    driver: bridge