apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopsengineers.devopslocal.to.server.com
spec:
  group: devopslocal.to.server.com
  scope: Namespaced
  names:
    plural: devopsengineers
    singular: devopsengineer
    shortNames:
      - devops
      - dls
    kind: DevOpsEngineer
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
              duration:
                type: string
                description: this DevOps roll it's always remote aviliable 
              platform:
                type: string
                discription: this roll are platform related absolutly aviliable 
              mode:
                type: string
                discription: DevOps Egineering is satrting to learn DevSecOps. MLOps. ALOPs

