apiVersion: devopslocal.to.server.com/v1
kind: DevOpsEngineer
metadata:
  name: test2-crd-context

spec:
  name: this is semple of crds
  duration: 4 month 24th january 2026
  platform: devopslocal.to.server.com
  mode: gain more knowleage in entire joureny 


