apiVersion: batch/v1
kind: CronJob

metadata:
  name: cron-job-backup
  namespace: nginx 

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cron-job-pod
          labels:
            app: cron-job-backup

        spec:
          containers:
            - name: schedule-backup
              image: busybox:latest
              imagePullPolicy: IfNotPresent

              command:
                - sh
                - -c
                - >
                  echo "this backup for cron jobs" &&
                  mkdir -p /backup-busybox-cron &&
                  mkdir -p /backup-data &&
                  cp -r /backup-data/ /backup-busybox-cron &&
                  date &&
                  echo "this step completed successfully"

              volumeMounts:
                - name: configer-storage-volume-source
                  mountPath: /backup-data

                - name: configer-storage-volume-backup
                  mountPath: /backup-busybox-cron

          restartPolicy: OnFailure

          volumes:
            - name: configer-storage-volume-source
              hostPath:
                path: /backup-data
                type: DirectoryOrCreate

            - name: configer-storage-volume-backup
              hostPath:
                path: /backup-busybox-cron
                type: DirectoryOrCreate
