apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx 
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-deployment-pods
      labels:
        app: nginx
        
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: volume-pvc

      volumes:        
        - name: volume-pvc
          persistentVolumeClaim: 
            claimName: local-pvc

