apiVersion: apps/v1                
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx 
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-deployment-pods
      labels:
        app: nginx
        
    spec:
      containers:                               # container creation using container and insaide create number of an pods 
      - name: nginx-container 
        image: nginx:latest                     # image which is provide from docker and base image for pods
        ports: 
        - containerPort: 80                     # expose port for communicate with out saide service's with together use 
        resources:                              # add probes for specifie and fix and minimum cpu and memory use 
          requests:                                 
            cpu: 100m
            memory: 165Mi
          limits:                                   # set an number of limits for pods resource's
            cpu: 200m
            memory: 265Mi
        livenessProbe:         # see the pods(containers) livenessprobes means live state
          httpGet:
            path: /
            port: 9000
      

        volumeMounts:
        - mountPath: /usr/share/nginx/html          
          name: volume-pvc

      volumes:        
        - name: volume-pvc
          persistentVolumeClaim: 
            claimName: local-pvc

