apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: nginx 
  labels:
    app: persistent-nginx-pod

spec:
  resources:
    requests:
      storage: 1Gi
  
  storageClassName: local-storage

  accessModes:
  - ReadWriteOnce
  