apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apache-manager-role-binding
  namespace: apache

subjects:
- kind: User
  name: apache-user-manager
  namespace: apache

roleRef:
  kind: Role
  name: apache-role-manager
  apiGroup: rbac.authorization.k8s.io 
