apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: mysql-ns

data: 
  MYSQL_DATABASE: "devopsdb" # never ever shear configmap file on github or publish on anywhere so this file is only demo file 
