apiVersion: v1
kind: Service
metadata:
  name: apache-service

spec:
  selector:
    labels:
      run: apache-service
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 9000 
