apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-server
spec:
  selector:
    app: apache-service

  type: ClusterIP

  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  ports:
    - protocol: TCP
      port: 80                # expose port from cluster which proved from kind (kubernetes in docker) 
      targetPort: 80          # all pods(container in saide ) are abale to lesion 80 port numer via TCP protocol with network 
    
