apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-server
spec:
  selector:
    app: apache-service

  type: ClusterIP

  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    
