name: CI FOR PYTHON APPLICATION 

on:
  push:
    branches:
      - main
    
jobs:
  build-and-run:            # this is build step
    runs-on: ubuntu-latest

    permissions:
     contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create auto versioning tag's
        id: version
        run: |
              LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)

              if [ -z "$LATEST_TAG" ]; then
                NEW_TAG="v1.0.0"
              else
                MAJOR=$(echo "$LATEST_TAG" | cut -d. -f1 | tr -d 'v')
                MINOR=$(echo "$LATEST_TAG" | cut -d. -f2)
                PATCH=$(echo "$LATEST_TAG" | cut -d. -f3)

                PATCH=$((PATCH + 1))
                NEW_TAG="v$MAJOR.$MINOR.$PATCH"
              fi  

              echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"      # final step, this is define new variable with called new_tag
              echo "now generated LATEST TAG IS: $NEW_TAG "
      
      - name: setup python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: install dependencies
        working-directory: ./server-app 
        run: |
              pip install -r requirements.txt  
              pip install pytest  

      - name: test python application code   # this is test step
        working-directory: ./server-app
        run: pytest ../tests/ -v # -v means vorbose display excuted dependencies and requirement's 
                

      - name: login to Dockerhub.io       # this section are login on DockerHub.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_LOGIN_PASS }}

      - name: build docker images
        working-directory: ./server-app
        run: |
          USERNAME=$(echo "${{ secrets.DOCKER_USER_NAME }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.version.outputs.new_tag }}

          docker build  \
           -t $USERNAME/app-images-python:$VERSION \
           -t $USERNAME/app-images-python:latest .    #  force lowercase
            

      - name: push images on Dockerhub.io with ther tag's
        run: |
          USERNAME=$(echo "${{ secrets.DOCKER_USER_NAME }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.version.outputs.new_tag }}

          docker push $USERNAME/app-images-python:$VERSION 
          docker push $USERNAME/app-images-python:latest       # force lowercase
      

      - name: github with configure bot user and email for reliable stage push
        run: |
              git config user.name "github-actions"
              git config user.email "githubactions@gmail.com"

              VERSION=${{ steps.version.outputs.new_tag }}

              git tag  -a $VERSION -m "release NEW AN: $VERSION TAG.."
              git push origin $VERSION  # push to  github tag repo in , not branche in
      