name: CD for python applicaation

on:
  workflow_run:
    workflows: ["CI FOR PYTHON APPLICATION"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-and-pull:
    runs-on: self-hosted
    environment: production

    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: login DockerHub.io
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_LOGIN_PASS}}

      - name: pull image from Dockerhub.io
        run: |
          USERNAME=$(echo "${{ secrets.DOCKER_USER_NAME }}" | tr '[:upper:]' '[:lower:]')

          docker pull $USERNAME/app-images-python$VERSION \
          docker pull  $USERNAME/app-images-python:latest

  up-and-run-container:
    runs-on: self-hosted
    needs: deploy-and-pull
    environment: staging

    permissions:
      contents: read

    steps:
      - name: checkout bug's
        uses: actions/checkout@v4

      - name: run's new container and remove old one's
        
        run: |
          cd server-app
          export DOCKER_USER_NAME=$(echo "${{ secrets.DOCKER_USER_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker compose down --remove-orphans
          docker compose up -d --build --wait
          
      - name: show latest tag's approval was attache 
        run: |
              echo "Deploy images:"
              docker inspect new-py-container --format='{{.config.image}}'  
  health-check:
    runs-on: self-hosted
    needs: up-and-run-container
    environment: release

    permissions:
      contents: read

    steps:
      - name: checkout all code
        uses: actions/checkout@v4

      - name: checkout container status
        run: |
          docker ps | grep new-py-container 
          docker images
          docker container ls   # it's show only running container's

      - name: check with curl command
        run: |
          echo "waiting for server response"
          for time in {1..15}; do
          curl --fail "http://${{ secrets.SERVER_HOST }}:9000/health" && break

          echo "curl fail at here , retrying with 3s"
          sleep 3s

          done 
          echo "app is runing on port......... >> 9000"
